// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNOk5F5blx6BtgR2xejXYoKDsodpI-y-g',
    appId: '1:678653533621:web:0ed446c9ac1b0d1bf08dfc',
    messagingSenderId: '678653533621',
    projectId: 'notification-b615c',
    authDomain: 'notification-b615c.firebaseapp.com',
    storageBucket: 'notification-b615c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ArHpcm4mU_ZiB5cBvyoPP8RFotQhHIs',
    appId: '1:678653533621:android:45ac8f16f431c376f08dfc',
    messagingSenderId: '678653533621',
    projectId: 'notification-b615c',
    storageBucket: 'notification-b615c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNOk5F5blx6BtgR2xejXYoKDsodpI-y-g',
    appId: '1:678653533621:web:2cb57bcf1d788d48f08dfc',
    messagingSenderId: '678653533621',
    projectId: 'notification-b615c',
    authDomain: 'notification-b615c.firebaseapp.com',
    storageBucket: 'notification-b615c.firebasestorage.app',
  );

}